#=========================================
# 공통
#=========================================
spring:
  profiles:
    active: local

  #=========================================
  # mysql
  #=========================================

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

#=========================================
# logging
#=========================================
#logging:
#  config: classpath:logback-${spring.profiles.active}.xml

